# Generated by Django 4.2.4 on 2023-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
