# Generated by Django 4.2.4 on 2023-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='archivo',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
