# Generated by Django 4.2.4 on 2023-09-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_alter_registros_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
